=== fireman98/B00P5Y_XMLGyak/B00P5y_0929/BB_ertodtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ermodell (A, B, C, A_B)>
<!ELEMENT A (Ab, Ac)>
<!ELEMENT Ab (Abx, Aby)>
<!ELEMENT Abx (#PCDATA)>
<!ELEMENT Aby (#PCDATA)>
<!ELEMENT Ac (Acd, Ace)>
<!ELEMENT Acd (#PCDATA)>
<!ELEMENT Ace (#PCDATA)>
<!ELEMENT B (Bb)>
<!ELEMENT Bb (Bbx, Bby)>
<!ELEMENT Bbx (#PCDATA)>
<!ELEMENT Bby (#PCDATA)>
<!ELEMENT C (Cb)>
<!ELEMENT Cb (#PCDATA)>
<!ELEMENT A_B (A_Bc)>
<!ELEMENT A_Bc (#PCDATA)>
<!ATTLIST A Aa CDATA #REQUIRED>
<!ATTLIST C Ca CDATA #REQUIRED>
<!ATTLIST B Ba CDATA #REQUIRED>
<!ATTLIST A id ID #REQUIRED>
<!ATTLIST B id ID #REQUIRED>
<!ATTLIST C id ID #REQUIRED>
<!ATTLIST A_B a CDATA #REQUIRED>
<!ATTLIST A_B b CDATA #REQUIRED>
<!ATTLIST B c CDATA #REQUIRED>

=== fireman98/B00P5Y_XMLGyak/B00P5y_0929/BB_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ermodell SYSTEM "BB_ertodtd.dtd">
<ermodell>
    <A Aa="1" id="a-1">
        <Ab>
            <Abx></Abx>
            <Aby></Aby>
        </Ab>
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>
    <B Ba="2" id="b-1" c="c-1">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>
    <C Ca="3" id="c-1">
        <Cb></Cb>
    </C>
    <A_B a="a-1" b="b-1">
        <A_Bc></A_Bc>
    </A_B>
</ermodell>
