=== fireman98/B00P5Y_XMLGyak/B00P5Y_1006/BB_ertoxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="A" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="b">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="x" type="xs:string" />
                                        <xs:element name="y" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Ac">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="d" type="xs:string" />
                                        <xs:element name="e" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="a" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="B" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="b">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="x" type="xs:string" />
                                        <xs:element name="y" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="a" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="C" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Cb" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="a" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="RelAB" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="c" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="Aid" type="xs:string" use="required" />
                        <xs:attribute name="Bid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="RelBC" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="Bid" type="xs:string" use="required" />
                        <xs:attribute name="Cid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== fireman98/B00P5Y_XMLGyak/B00P5Y_1006/BB_xsdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BB_ertoxsd.xsd">
    <A a="a1">
        <b>
            <x>X1</x>
            <y>Y1</y>
        </b>
        <Ac>
            <d>D1</d>
            <e>E1</e>
        </Ac>
    </A>
    <B a="a2">
        <b>
            <x>X2</x>
            <y>Y2</y>
        </b>
    </B>
    <C a="a3">
        <Cb>Cb</Cb>
    </C>
    <RelAB Aid="a1" Bid="a2">
        <c>C1</c>
    </RelAB>
    <RelBC Bid="a2" Cid="a3" />
</root>
