=== fireman98/B00P5Y_XMLGyak/B00P5Y_1006/BB_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="konyvek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="konyv" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cim" type="xs:string"></xs:element>
                            <xs:element name="ev" type="xs:unsignedShort"></xs:element>
                            <xs:element name="kiado" type="xs:string"></xs:element>
                            <xs:element name="szerzo" type="xs:string" maxOccurs="unbounded"></xs:element>
                            <xs:element name="kivonat" type="xs:string" minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== fireman98/B00P5Y_XMLGyak/B00P5Y_1006/BB_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BB_konyv.xsd">
    <konyv id="k01">
        <cim>
         Refactoring        
         </cim>
        <ev>2018</ev>
        <kiado>Addison-Wesley Professional</kiado>
        <szerzo>Martin Fowler</szerzo>
        <szerzo>Kent Beck</szerzo>
        <kivonat>"Whenever you read Refactoring], it's time to read it again. And if you haven't read it yet, please do before writing another line of code." -David Heinemeier Hansson, Creator of Ruby on Rails, Founder and CTO at Basecamp.</kivonat>
    </konyv>
    <konyv id="k02">
        <cim>
            Introduction to Algorithms        
        </cim>
        <ev>2009</ev>
        <kiado>MIT Press</kiado>
        <szerzo>Thomas H. Cormen</szerzo>
        <szerzo>Clifford Stein</szerzo>
        <szerzo>Ronald L. Rivest</szerzo>
        <szerzo>Charles E. Leiserson</szerzo>
        <kivonat>Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor. Introduction to Algorithms uniquely combines rigor and comprehensiveness. The book covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers. Each chapter is relatively self-contained and can be used as a unit of study. The algorithms are described in English and in a pseudocode designed to be readable by anyone who has done a little programming. The explanations have been kept elementary without sacrificing depth of coverage or mathematical rigor.The first edition became a widely used text in universities worldwide as well as the standard reference for professionals. The second edition featured new chapters on the role of algorithms, probabilistic analysis and randomized algorithms, and linear programming. The third edition has been revised and updated throughout. It includes two completely new chapters, on van Emde Boas trees and multithreaded algorithms, substantial additions to the chapter on recurrence (now called "Divide-and-Conquer"), and an appendix on matrices. It features improved treatment of dynamic programming and greedy algorithms and a new notion of edge-based flow in the material on flow networks. Many new exercises and problems have been added for this edition. As of the third edition, this textbook is published exclusively by the MIT Press. The hardcover edition does not include a dust jacket.</kivonat>

    </konyv>
    <konyv id="k03">
        <cim>
            Soft Skills: The software developer's life manual        
        </cim>
        <ev>2014</ev>
        <kiado>Manning Publications</kiado>
        <szerzo>John Sonmez</szerzo>
    </konyv>
</konyvek>
