=== fireman98/B00P5Y_XMLGyak/B00P5Y_1013/BB_orarend1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="oraID">
        <xs:restriction base="xs:string">
            <xs:length value="5" />
            <xs:pattern value="[a-zA-Z][a-zA-Z][0-9][0-9][a-zA-Z]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="orarend">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ora" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="targy" type="xs:string"></xs:element>
                            <xs:element name="idopont">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nap" type="xs:string"></xs:element>
                                        <xs:element name="tol" type="xs:unsignedShort"></xs:element>
                                        <xs:element name="ig" type="xs:unsignedShort"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="helyszin" type="xs:string"></xs:element>
                            <xs:element name="oktato" type="xs:string"></xs:element>
                            <xs:element name="szak" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="oraID" use="required"></xs:attribute>
                        <xs:attribute name="tipus" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueID">
            <xs:selector xpath=".//*" />
            <xs:field xpath="@id" />
        </xs:unique>
    </xs:element>
</xs:schema>

=== fireman98/B00P5Y_XMLGyak/B00P5Y_1013/BB_orarend1.xml
<?xml version="1.0" encoding="utf-8"?>

<orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BB_orarend1.xsd">
    <ora id="xm01t" tipus="elmélet">
        <targy>Adatkezelés XML környezetben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>1200</tol>
            <ig>1400</ig>
        </idopont>
        <helyszin>I/A2 fsz.</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>PTI</szak>
    </ora>

    <ora id="xm02t" tipus="gyakorlat">
        <targy>Idegennyelv 1</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>1600</tol>
            <ig>1800</ig>
        </idopont>
        <helyszin>In/202 InA1/ 11 A1 magasfsz. 11</helyszin>
        <oktato>Dorkó Dóra</oktato>
        <szak>PTI</szak>
    </ora>

    <ora id="xm03t" tipus="gyakorlat">
        <targy>Adatkezelés XML környezetben</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>1000</tol>
            <ig>1200</ig>
        </idopont>
        <helyszin>In/202 In II. em. 202</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>PTI</szak>
    </ora>
</orarend>
