=== fireman98/B00P5Y_XMLGyak/XMLTaskB00P5Y/XMLSchemaB00P5Y.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="allatok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="allat" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                                        <xs:element name="nem" type="xs:string"></xs:element>
                                        <xs:element name="faj">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="orszag" type="xs:string"></xs:element>
                                                    <xs:element name="torzs" type="xs:string"></xs:element>
                                                    <xs:element name="osztaly" type="xs:string"></xs:element>
                                                    <xs:element name="rend" type="xs:string"></xs:element>
                                                    <xs:element name="csalad" type="xs:string"></xs:element>
                                                    <xs:element name="faj" type="xs:string"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="szuletes-ideje" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="aid" type="xs:string" use="required"></xs:attribute>
                                    <xs:attribute name="eid" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="gondozok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="gondozo" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string"></xs:element>
                                        <xs:element name="nem" type="xs:string"></xs:element>
                                        <xs:element name="fizetes" type="xs:int"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="szemelyi-szam" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="elohelyek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="elohely" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="terulet" type="xs:float"></xs:element>
                                        <xs:element name="tipus" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="eid" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="gondozasok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="gondozas" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="idopont" type="xs:string"></xs:element>
                                        <xs:element name="megjegyzes" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="gid" type="xs:string" use="required"></xs:attribute>
                                    <xs:attribute name="szemelyi-szam" type="xs:string" use="optional"></xs:attribute>
                                    <xs:attribute name="aid" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="takaritasok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="takaritas" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="idopont" type="xs:string"></xs:element>
                                        <xs:element name="megjegyzes" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="tid" type="xs:string" use="required"></xs:attribute>
                                    <xs:attribute name="eid" type="xs:string" use="required"></xs:attribute>
                                    <xs:attribute name="szemelyi-szam" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="gondozok-telefonszamok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="telefonszam" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="telefonszam" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="telid" type="xs:string" use="required"></xs:attribute>
                                    <xs:attribute name="szemelyi-szam" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="latogatasok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="latogatas" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipus"></xs:element>
                                        <xs:element name="idopont"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="jegyszam" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="nyitvatartasok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nyitvatartas" minOccurs="12" maxOccurs="12">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nyitas" type="xs:string"></xs:element>
                                        <xs:element name="zaras" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="honap" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="key_allat">
            <xs:selector xpath="allatok/allat"></xs:selector>
            <xs:field xpath="@aid"></xs:field>
        </xs:key>
        <xs:key name="key_gondozo">
            <xs:selector xpath="gondozok/gondozo"></xs:selector>
            <xs:field xpath="@szemelyi-szam"></xs:field>
        </xs:key>
        <xs:key name="key_elohely">
            <xs:selector xpath="elohelyek/elohely"></xs:selector>
            <xs:field xpath="@eid"></xs:field>
        </xs:key>
        <xs:key name="key_gondozas">
            <xs:selector xpath="gondozasok/gondozas"></xs:selector>
            <xs:field xpath="@gid"></xs:field>
        </xs:key>
        <xs:key name="key_takaritas">
            <xs:selector xpath="takaritasok/takaritas"></xs:selector>
            <xs:field xpath="@tid"></xs:field>
        </xs:key>
        <xs:key name="key_gondozo-telefonszam">
            <xs:selector xpath="gondozok-telefonszamok/telefonszam"></xs:selector>
            <xs:field xpath="@telid"></xs:field>
        </xs:key>
        <xs:key name="key_latogatas">
            <xs:selector xpath="latogatasok/latogatas"></xs:selector>
            <xs:field xpath="@jegyszam"></xs:field>
        </xs:key>
        <xs:key name="key_nyitvatartas">
            <xs:selector xpath="nyitvatartasok/nyitvatartas"></xs:selector>
            <xs:field xpath="@honap"></xs:field>
        </xs:key>

        <xs:keyref name="FK_allat_elohely" refer="key_elohely">
            <xs:selector xpath="allatok/allat"></xs:selector>
            <xs:field xpath="@eid"></xs:field>
        </xs:keyref>
        <xs:keyref name="FK_gondozas_gondozo" refer="key_gondozo">
            <xs:selector xpath="gondozasok/gondozas"></xs:selector>
            <xs:field xpath="@szemelyi-szam"></xs:field>
        </xs:keyref>
        <xs:keyref name="FK_gondozas_allat" refer="key_allat">
            <xs:selector xpath="gondozasok/gondozas"></xs:selector>
            <xs:field xpath="@aid"></xs:field>
        </xs:keyref>
        <xs:keyref name="FK_takaritas_elohely" refer="key_elohely">
            <xs:selector xpath="takaritasok/takaritas"></xs:selector>
            <xs:field xpath="@eid"></xs:field>
        </xs:keyref>
        <xs:keyref name="FK_takaritas_gondozo" refer="key_gondozo">
            <xs:selector xpath="takaritasok/takaritas"></xs:selector>
            <xs:field xpath="@szemelyi-szam"></xs:field>
        </xs:keyref>
        <xs:keyref name="FK_gondozok-telefonszamok_gondozo" refer="key_gondozo">
            <xs:selector xpath="gondozok-telefonszamok/telefonszam"></xs:selector>
            <xs:field xpath="@szemelyi-szam"></xs:field>
        </xs:keyref>

    </xs:element>
</xs:schema>

=== fireman98/B00P5Y_XMLGyak/XMLTaskB00P5Y/XMLB00P5Y.xml
<?xml version="1.0" encoding="UTF-8"?>


<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaB00P5Y.xsd">
    <allatok>
        <allat aid="a-1" eid="e-5">
            <nev>Pihe</nev>
            <nem>Hím</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Ragadozók</rend>
                <csalad>Macskafélék</csalad>
                <faj>Vadmacska</faj>
            </faj>
            <szuletes-ideje>
                2021.04.20.
            </szuletes-ideje>
        </allat>
        <allat aid="a-2" eid="e-5">
            <nev>Cirmi</nev>
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Ragadozók</rend>
                <csalad>Macskafélék</csalad>
                <faj>Vadmacska</faj>
            </faj>
            <szuletes-ideje>
                2021.08.19.
            </szuletes-ideje>
        </allat>
        <allat aid="a-3" eid="e-3">
            <nev>Füles</nev>
            <nem>Hím</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Ragadozók</rend>
                <csalad>Kutyafélék</csalad>
                <faj>Farkas</faj>
            </faj>
            <szuletes-ideje>
                2016.05.11.
            </szuletes-ideje>
        </allat>
        <allat aid="a-4" eid="e-3">
            <nev>Vadóc</nev>
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Ragadozók</rend>
                <csalad>Kutyafélék</csalad>
                <faj>Farkas</faj>
            </faj>
            <szuletes-ideje>
                2017.08.30.
            </szuletes-ideje>
        </allat>
        <allat aid="a-5" eid="e-3">
            <nev>Vadóc</nev>
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Ragadozók</rend>
                <csalad>Kutyafélék</csalad>
                <faj>Farkas</faj>
            </faj>
            <szuletes-ideje>
                2017.08.30.
            </szuletes-ideje>
        </allat>
        <allat aid="a-6" eid="e-2">
            <nev>Béla</nev>
            <nem>Him</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Párosujjú patások</rend>
                <csalad>Disznófélék</csalad>
                <faj>Vaddisznó</faj>
            </faj>
            <szuletes-ideje>
                2016.10.26.
            </szuletes-ideje>
        </allat>
        <allat aid="a-7" eid="e-2">
            <nev>Barnabás</nev>
            <nem>Him</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Párosujjú patások</rend>
                <csalad>Disznófélék</csalad>
                <faj>Vaddisznó</faj>
            </faj>
            <szuletes-ideje>
                2016.10.26.
            </szuletes-ideje>
        </allat>
        <allat aid="a-8" eid="e-2">
            <nev>Cecília</nev>
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Párosujjú patások</rend>
                <csalad>Disznófélék</csalad>
                <faj>Vaddisznó</faj>
            </faj>
            <szuletes-ideje>
                2015.12.03.
            </szuletes-ideje>
        </allat>
        <allat aid="a-9" eid="e-2">
            <nev>Jessica</nev>
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Emlősök</osztaly>
                <rend>Párosujjú patások</rend>
                <csalad>Disznófélék</csalad>
                <faj>Vaddisznó</faj>
            </faj>
            <szuletes-ideje>
                2018.01.26.
            </szuletes-ideje>
        </allat>
        <allat aid="a-10" eid="e-1">
            <nev>Totyi</nev>
            <nem>Hím</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Pingvinalakúak</rend>
                <csalad>Pingvinfélék</csalad>
                <faj>Császárpingvin</faj>
            </faj>
            <szuletes-ideje>
                2011.05.11.
            </szuletes-ideje>
        </allat>
        <allat aid="a-11" eid="e-1">
            <nev>Tipegő</nev>
            <nem>Hím</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Pingvinalakúak</rend>
                <csalad>Pingvinfélék</csalad>
                <faj>Császárpingvin</faj>
            </faj>
            <szuletes-ideje>
                2013.07.11.
            </szuletes-ideje>
        </allat>
        <allat aid="a-12" eid="e-4">
            <nev>Zsolti</nev>
            <nem>Hím</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Pingvinalakúak</rend>
                <csalad>Úszólábúak</csalad>
                <faj>Fóka</faj>
            </faj>
            <szuletes-ideje>
                2015.05.06.
            </szuletes-ideje>
        </allat>
        <allat aid="a-13" eid="e-4">
            <nev>Szandi</nev>
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Pingvinalakúak</rend>
                <csalad>Úszólábúak</csalad>
                <faj>Fóka</faj>
            </faj>
            <szuletes-ideje>
                2014.12.05.
            </szuletes-ideje>
        </allat>
        <allat aid="a-14" eid="e-6">
            <nev>Fütyülős</nev>
            <nem>Hím</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Lúdalakúak</rend>
                <csalad>Récefélék</csalad>
                <faj>Tőkés réce</faj>
            </faj>
            <szuletes-ideje>
                2018.03.11.
            </szuletes-ideje>
        </allat>
        <allat aid="a-15" eid="e-1">
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Pingvinalakúak</rend>
                <csalad>Pingvinfélék</csalad>
                <faj>Császárpingvin</faj>
            </faj>
            <szuletes-ideje>
                2019.11.15.
            </szuletes-ideje>
        </allat>
        <allat aid="a-16" eid="e-6">
            <nem>Hím</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Lúdalakúak</rend>
                <csalad>Récefélék</csalad>
                <faj>Tőkés réce</faj>
            </faj>
            <szuletes-ideje>
                2019.03.14.
            </szuletes-ideje>
        </allat>
        <allat aid="a-17" eid="e-6">
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Lúdalakúak</rend>
                <csalad>Récefélék</csalad>
                <faj>Tőkés réce</faj>
            </faj>
            <szuletes-ideje>
                2019.05.31.
            </szuletes-ideje>
        </allat>
        <allat aid="a-18" eid="e-6">
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Lúdalakúak</rend>
                <csalad>Récefélék</csalad>
                <faj>Tőkés réce</faj>
            </faj>
            <szuletes-ideje>
                2017.03.11.
            </szuletes-ideje>
        </allat>
        <allat aid="a-19" eid="e-6">
            <nem>Nőstény</nem>
            <faj>
                <orszag>Állatok</orszag>
                <torzs>Gerinchúrosok</torzs>
                <osztaly>Madarak</osztaly>
                <rend>Lúdalakúak</rend>
                <csalad>Récefélék</csalad>
                <faj>Tőkés réce</faj>
            </faj>
            <szuletes-ideje>
                2016.03.20.
            </szuletes-ideje>
        </allat>
    </allatok>
    <gondozok>
        <gondozo szemelyi-szam="123456AA">
            <nev>Dolgos Jóska</nev>
            <nem>Férfi</nem>
            <fizetes>150000</fizetes>
        </gondozo>
        <gondozo szemelyi-szam="123456BA">
            <nev>Radó Fülöp</nev>
            <nem>Férfi</nem>
            <fizetes>140000</fizetes>
        </gondozo>
        <gondozo szemelyi-szam="654321BA">
            <nev>Nyers Gabriella</nev>
            <nem>Nő</nem>
            <fizetes>140000</fizetes>
        </gondozo>
        <gondozo szemelyi-szam="654323BA">
            <nev>Süveges Krisztina</nev>
            <nem>Nő</nem>
            <fizetes>160000</fizetes>
